version: "3.9"

services:
  desafio:
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "8080:8090"
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3.9.9-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      SPRING_RABBITMQ_HOST: my-rabbit